### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by psc001** [rfos/CakeTicket#3]
# Planejamento
Com o objetivo de elaborar as funcionalidades básicas e avançadas do sistema, abro por meio deste um tópico para discussão e planejamento dos mesmos. Uma vez o planejamento iniciado, poderemos, a partir deste: analisar e priorizar os objetivos.

Gostaria de pedir que não prenderem a detalhes demasiadamente pequenos e que possam desviar o foco. Para elucida-los melhor, deixo aqui um trecho do livro _Scrum - Gestão Ágil para projetos_:
> #### "Analogia do horizonte
> Digamos que você está olhando para uma cidade, e vê desde as construções,
> carros e pessoas que estão mais próximos de você até o que está no horizonte distante.
> Ao olhar para o que está mais próximo, você consegue descrever o que vê com
> um excelente nível de detalhes. O que está um pouco mais distante, você ainda pode
> descrever com um bom nível de detalhes, ainda que menor. Mas à medida que olha
> para mais longe, os detalhes que pode utilizar em sua descrição vão gradualmente
> diminuindo. Se você então tentar descrever o que vê com um alto nível de detalhes,
> ao caminhar em direção ao horizonte, verá que sua descrição não corresponde inteiramente
> à realidade, e que você deverá modificar essa descrição. Na verdade, para
> quanto mais distante você estiver olhando, mais incorreta estará essa sua descrição
> detalhada, e maior será o desperdício gerado. [...]"

Então que se inicie a <s>Guerra</s> discussão!

**Comment by francisreboucas** [comment]
Bem eu criei um markdrown para isso...vou postar aqui para ver o que vai rolar.

#CakeTicket - Webdesk
## Principais Funcionalidades
Podemos nos basear nos seguintes pilares:
- Customização
- Integração
- Atendimento
- Gerenciamento e Controle


## Customização

### Campos customizados
Permitir a escolha de quais serão os campos na criação de tickets customizando a ferramenta para atender as necessidades de diversas áreas.

### Customização do cadastro de clientes
Permitir a escolha de quais campos cadastrais o perfil do seu cliente precisa ter, como telefone, endereço, site e outros campos personalizados.
Após cadastramento do usuário, o mesmo deverá receber um email para confirmar o seu cadastro validando o endereço de email.

### Controle de Acesso
Administradores podem criar novos  agentes e também bloqueá-los ou marca-los como excluído.

### Acesso diferenciado por perfil
Cada perfil possui um nível de acesso:  Enquanto agentes apenas interagem nos
tickets, administradores podem também gerenciar e customizar a ferramenta.

### Atribuição de Categorias por agente
Possibilidade de categorizar os agentes e os agentes podem ser responsáveis por categorias específicas.

### Personalização
Customize a ferramenta com o logo da  sua empresa e com a paleta de cores que preferir.

## Integração
Permitir a importação e exportação de dados por meio de xml, csv dentre outros.

## Atendimento

### Agentes por categoria
Os tickets devem ser encaminhados  apenas para os agentes responsáveis por determinadas categorias.
Neste caso os agentes deverão ser agrupados por "equipe"", exemplo: desenvolvimento, suporte em campo, suporte por telefone, suporte para Telecom e suporte de terceiros (assistência técnica e outros).

### Notificações por email
O sistema deve enviar uma notificação por e-mail  sempre que um novo ticket for criado ou tiver uma nova resposta.

##Gerenciamento e Controle
### Prazos e prioridades para os tickets
Para cada ticket o agente pode atribuir uma prioridade e também uma data final para ele ser concluído. 
Essa característica deverá ser implementada definindo o SLA para cada tipo de chamado.


### Visão Geral
Ao acessar o sistema, tenha uma visão geral do que está acontecendo, com
gráficos e acessos rápidos, além de status dos tickets por agente.
### Controle dos tickets por status
Permitir acompanhamento quando um ticket foi respondido pelo cliente e aguarda nova resposta de um agente.
### Relatórios
Permitir acompanhamento do desempenho de seus tickets em relatórios completos: tickets por categoria, cliente e empresa.

**Comment by andrecavallari** [comment]
Já podemos jogar o skeleton do app aqui, ele já integra tudo que for necessário para rodar... Vejam os requisitos para rodar o cake 3.0 e se adequem (PHP 5.4.16+, mod. mbstring e intl) para darmos o pontapé inicial.

Eu já tenho um layout admin pronto para usar no Cake 3.0, está em formato de plugin, basta usar seu componente para usar todas as funcionalidades do layout, só falta eu documentar... mas já vou fazer isso essa semana e deixo tudo pronto para o uso, mas se quiserem se adiantar o package é andrecavallari/painel

**Comment by rfos** [comment]
Eu confesso que estou perdido no Cake 3 (buáááá)

**Comment by andrecavallari** [comment]
Comece pelo composer... estude composer, git... e vai ver como o cake 3 é MUITO melhor que o 2.x

####Vantagens:
namespaces
psr´s
traits
php 5.4+

**Comment by rfos** [comment]
Eu fiz algumas modificações no arquivo das funcionalidades que o @francisreboucas criou, seria legal todo mundo contribuir nesse documento.

Outra coisa bem importante é a estrutura da base de dados que ainda não pensamos como vamos fazer.. 

Vamos hospedar o projeto onde?

**Comment by andrecavallari** [comment]
Hospedagem deve ser em algum lugar que tenha PHP 5.4 com o módulo intl ativado, senão esquece... de preferência alguém que tenha um espacinho que possa emprestar em alguma cloud...

**Comment by rfos** [comment]
No http://digitalocean.com tem um host de 5USD cloud, dá pra instalar lá..  só que é 512 de RAM, pode rodar?

**Comment by andrecavallari** [comment]
enquanto é somente projeto roda bem de boa...

**Comment by rfos** [comment]
Vou configurar entao...

**Comment by andrecavallari** [comment]
Também é possível instalar git no digitalocean e fazer deploys via git

**Comment by rfos** [comment]
será que é suficiente ?
http://192.241.160.67/info.php

**Comment by rfos** [comment]
Acho que falta uma coisa.. to instalando ainda..

**Comment by francisreboucas** [comment]
Reinaldo, vi as alterações no documento de funcionalidades, perfeito. Acho que já temos algo para iniciar. Não podemos nos ater a muitos detalhes porque assim perdemos tempo demais. Agora já podemos definir qual tem mais BV, montar um backlog para definir as sprints para depois diminuir o nível de detalhamento.

**Comment by psc001** [comment]
Opa vejo que o @francisreboucas ta trazendo o Scrum para o projeto. :+1: 
Já podemos esboçar as primeiras migrations para as tabelas mais básicas.

E já aproveitando, creio que os tickets sofreram atualizações e mudanças de estados com o tempo.
Um Uml poderá representar melhor, mas deixarei uma ideia do que imaginei...

tickets hasMany ticket_updates. (contendo toda comunicação e alteração do ticket)
tickets belongsTo users. (em diversas instâncias: Criador, Responsável, etc.. )
tickets hasOne status. ( Aberto, Fechado, Negado, Cancelado, etc.. )

Outras tabelas auxiliares tbm são bem vindas, como Categorias e Setores para direcionar o ticket ao local correto!
